config/routes.rb
Rails.application.routes.draw do
  resources :tags
  
  resources :books
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "books#menu"
  get 'books#index', to: 'books#index'
end

app/models/book.rb
class Book < ApplicationRecord
    has_one :tag
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
      @books = Book.all
    if params[:pricesortasc]
      @books = @books.order(:price)          # sort by price ascending
    end
    if params[:pricesortdesc]
      @books = @books.order(price: :desc)    # sort by price descending
    end
    if params[:freebooks]
      @books = @books.where("price = 0")     # select free books
    end
    if params[:tag2]
      @books = Book.joins(:tag).where(:tags => {:tag2 => 'true'})   # list books with tag2 checked
    end
    if params[:tag1]
      @books = Book.joins(:tag).where(:tags => {:tag1 => 'true'})   # list books with tag1 checked
    end
    if params[:tag3]
        @books = Book.joins(:tag).where(:tags => {:tag3 => 'true'})  # list books with tag3 checked
    end
    if params[:tag1tag2]
        @books = Book.joins(:tag).where(:tags => {:tag1 => 'true', :tag2 => 'true'})  # list books with tag1 and tag2 checked
    end
    if params[:tag1tag3]
        @books = Book.joins(:tag).where(:tags => {:tag1 => 'true', :tag3 => 'true'})  # list books with tag1 and tag3 checked
    end
    if params[:tag2tag3]
      @books = Book.joins(:tag).where(:tags => {:tag2 => 'true', :tag3 => 'true'})    # list books with tag2 and tag3 checked
    end
    if params[:tag2tag3pr56]
      @books = Book.joins(:tag).where(:tags => {:tag2 => 'true', :tag3 => 'true'}, :books => { :price => '56'})      # list books with tag2 and tag3 checked and price = 56
    end
    if params[:tag2tag3pr0]
      @books = Book.joins(:tag).where(:tags => {:tag2 => 'true', :tag3 => 'true'}, :books => { :price => '0'})       # list books with tag2 and tag3 checked and price = 0
    end
    if params[:tag2tag3prg0]
      @books = Book.joins(:tag).where([ 'tags.tag2 = true AND  tags.tag3 = true AND books.price >=  0'])             # list books with tag2 and tag3 checked and price >= 0
    end
    if params[:tag1tag2prg0]
      @books = Book.joins(:tag).where([ 'tags.tag1 = true AND  tags.tag2 = true AND books.price >=  0'])             # list books with tag2 and tag3 checked and price >= 0
    end
    
    
    # render json: @books
    
    
    ###############################                                                  ################################
    ###############################  QUERIES TO BE IMPLEMENTED FROM FROTNEND SIDE    ################################
    ###############################                                                  ################################
    # @books = @books.sort_by &:created_at                                                                           # sort by created at
    # @books = @books.order(:price)                                                                                  # sort by price ascending
    # @books = @books.order(price: :desc)                                                                            # sort by price descending
    # @books = @books.where("price = 0")                                                                             # select free books
    # @books = @books.where("id = 1")                                                                                # select books through id
    # @books = Book.joins(:tag).where(:tags => {:tag2 => 'true'})                                                    # list books with tag2 checked
    # @books = Book.joins(:tag).where(:tags => {:tag1 => 'true'})                                                    # list books with tag1 checked
    # @books = Book.joins(:tag).where(:tags => {:tag3 => 'true'})                                                    # list books with tag3 checked
    # @books = Book.joins(:tag).where(:tags => {:tag1 => 'true', :tag2 => 'true'})                                   # list books with tag1 and tag2 checked
    # @books = Book.joins(:tag).where(:tags => {:tag1 => 'true', :tag3 => 'true'})                                   # list books with tag1 and tag3 checked
    # @books = Book.joins(:tag).where(:tags => {:tag2 => 'true', :tag3 => 'true'})                                   # list books with tag2 and tag3 checked
    # @books = Book.joins(:tag).where(:tags => {:tag2 => 'true', :tag3 => 'true'}, :books => { :price => '56'})      # list books with tag2 and tag3 checked and price = 56
    # @books = Book.joins(:tag).where(:tags => {:tag2 => 'true', :tag3 => 'true'}, :books => { :price => '0'})       # list books with tag2 and tag3 checked and price = 0
    # @books = Book.joins(:tag).where([ 'tags.tag2 = true AND  tags.tag3 = true AND books.price >=  0'])             # list books with tag2 and tag3 checked and price >= 0
  end


  
    

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :description, :price)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
  <p>
    <strong>Title:</strong>
    <%= book.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= book.description %>
  </p>

  <p>
    <strong>Price: $</strong>
    <%= book.price %>
  </p>

</div>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Show this book", @book %> |
  <%= link_to "Back to Main Menu", root_path %>
</div>

app/views/books/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Books</h1>

<li>
<%= link_to "Home", root_path %>

<div id="books">
  <% @books.each do |book| %>
    <%= render book %>
    <p>
      <%= link_to "Show this book", book %>
    </p>
  <% end %>
</div>

<%= link_to "New book", new_book_path %>

app/views/books/menu.html.erb
<p style="color: green"><%= notice %></p>

<h1>MENU</h1>

<li>
<%= link_to "List All Books According to Price Ascending", books_path(pricesortasc: true) %>
<li>
<%= link_to "List All Books According to Price Descending", books_path(pricesortdesc: true) %>
<li>
<%= link_to "List All Free Books", books_path(freebooks: true) %> 
<li>
<%= link_to "List All Books with Tag 2", books_path(tag2: true) %>
<li>
<%= link_to "List All Books with Tag 1", books_path(tag1: true) %>
<li>
<%= link_to "List All Books with Tag 3", books_path(tag3: true) %>
<li>
<%= link_to "List All Books with Tag 1 and Tag 2", books_path(tag1tag2: true) %>
<li>
<%= link_to "List All Books with Tag 1 and Tag 3", books_path(tag1tag3: true) %>
<li>
<%= link_to "List All Books with Tag 2 and Tag 3", books_path(tag2tag3: true) %>
<li>
<%= link_to "List All Books with Tag 2, Tag 3 and price 56", books_path(tag2tag3pr56: true) %>
<li>
<%= link_to "List All Books with Tag 2, Tag 3 and price greater than Zero", books_path(tag2tag3prg0: true) %>
<li>
<%= link_to "List All Books with Tag 1, Tag 2 and price greater than Zero", books_path(tag1tag2prg0: true) %>

<h1>ASSIGN TAGS</h1>
<li>
<%= link_to "Assign Tags to Books", tags_path %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Back to Main Menu", root_path %>
</div>

app/views/books/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @book %>

<div>
  <%= link_to "Edit this book", edit_book_path(@book) %> |
  <%= link_to "Back to main  Menu", root_path %>

  <%= button_to "Destroy this book", @book, method: :delete %>
</div>